/**
 * action types gather
 */
const TYPES = {
    LOGIN: "LOGIN",
    LOGINOUT: "LOGINOUT",
    FETCH_REQUEST: "FETCH_REQUEST",
    FETCH_FAILURE: "FETCH_FAILURE",
    FETCH_RECEIVE: "FETCH_RECEIVE",
    FETCH_ERR: "FETCH_ERR",
    GO_NEWS_DETAIL: "GO_NEWS_DETAIL"
}

export default TYPES;