/**
 * action types gather
 */
const TYPES = {
    TO_LOGIN: 'TO_LOGIN',
    LOGIN: "LOGIN",
    LOGINOUT: "LOGINOUT",
    FETCH_REQUEST: "FETCH_REQUEST",
    FETCH_FAILURE: "FETCH_FAILURE",
    FETCH_RECEIVE: "FETCH_RECEIVE",
    FETCH_ERR: "FETCH_ERR",
    TO_NEWS_TAB: "TO_NEWS_TAB",
    TO_COMMENT: "TO_COMMENT",
    TO_NEWS_DETAIL: "TO_NEWS_DETAIL"
}

export default TYPES;